DEFAULT_ESTIMATION_NOTE = (
    "These values are practical estimates based on a typical single waste item and should "
    "be treated as guidance, not exact measured output."
)

OBJECT_INFO = {
    "BIODEGRADABLE": {
        "title": "Biodegradable Waste",
        "category": "Organic",
        "description": "Food scraps or natural waste that can break down safely over time.",
        "handling_tip": "Keep it separate from dry waste so it can be composted.",
        "waste_nature": "Biodegradable",
        "is_biodegradable": True,
        "is_recyclable": False,
        "recyclability": "Non-recyclable",
        "estimated_item_weight_kg": 0.25,
        "estimated_energy_recovery_kwh_per_kg": 0.55,
        "energy_recovery_method": "Biogas or organic waste-to-energy",
        "estimation_note": DEFAULT_ESTIMATION_NOTE,
    },
    "CARDBOARD": {
        "title": "Cardboard",
        "category": "Dry Recyclable",
        "description": "Boxes and thick paperboard packaging that can usually be recycled.",
        "handling_tip": "Flatten it and keep it dry before recycling.",
        "waste_nature": "Biodegradable",
        "is_biodegradable": True,
        "is_recyclable": True,
        "recyclability": "Recyclable",
        "estimated_item_weight_kg": 0.18,
        "estimated_energy_recovery_kwh_per_kg": 4.2,
        "energy_recovery_method": "Refuse-derived fuel or paper fiber energy recovery",
        "estimation_note": DEFAULT_ESTIMATION_NOTE,
    },
    "GLASS": {
        "title": "Glass",
        "category": "Dry Recyclable",
        "description": "Bottles or jars made of glass that are commonly recyclable.",
        "handling_tip": "Rinse if needed and handle carefully to avoid breakage.",
        "waste_nature": "Non-biodegradable",
        "is_biodegradable": False,
        "is_recyclable": True,
        "recyclability": "Recyclable",
        "estimated_item_weight_kg": 0.30,
        "estimated_energy_recovery_kwh_per_kg": 0.0,
        "energy_recovery_method": "Not typically used for energy recovery; recycling is preferred",
        "estimation_note": DEFAULT_ESTIMATION_NOTE,
    },
    "METAL": {
        "title": "Metal",
        "category": "Dry Recyclable",
        "description": "Metal cans or containers that can often go into recycling streams.",
        "handling_tip": "Clean the container and avoid mixing with food waste.",
        "waste_nature": "Non-biodegradable",
        "is_biodegradable": False,
        "is_recyclable": True,
        "recyclability": "Recyclable",
        "estimated_item_weight_kg": 0.08,
        "estimated_energy_recovery_kwh_per_kg": 0.1,
        "energy_recovery_method": "Very low; recycling is usually the better route",
        "estimation_note": DEFAULT_ESTIMATION_NOTE,
    },
    "PAPER": {
        "title": "Paper",
        "category": "Dry Recyclable",
        "description": "Newspapers, office paper, and similar paper products.",
        "handling_tip": "Keep paper dry and free from oil or food contamination.",
        "waste_nature": "Biodegradable",
        "is_biodegradable": True,
        "is_recyclable": True,
        "recyclability": "Recyclable",
        "estimated_item_weight_kg": 0.03,
        "estimated_energy_recovery_kwh_per_kg": 4.0,
        "energy_recovery_method": "Paper waste energy recovery or fuel pellets",
        "estimation_note": DEFAULT_ESTIMATION_NOTE,
    },
    "PLASTIC": {
        "title": "Plastic",
        "category": "Dry Recyclable",
        "description": "Plastic bottles, containers, or packaging depending on local recycling rules.",
        "handling_tip": "Rinse the item and check local recycling acceptance.",
        "waste_nature": "Non-biodegradable",
        "is_biodegradable": False,
        "is_recyclable": True,
        "recyclability": "Recyclable",
        "estimated_item_weight_kg": 0.025,
        "estimated_energy_recovery_kwh_per_kg": 8.8,
        "energy_recovery_method": "Plastic waste-to-energy or pyrolysis",
        "estimation_note": DEFAULT_ESTIMATION_NOTE,
    },
}
